### ISSUE TITLE
Matrix conversion is unbearbly slow--but easy work around

### ISSUE THREAD

**Issue by tbenst** [severinson/H5Sparse.jl#7]
Perhaps can just change docs to recommend `sparse(Matrix(A))` instead of `Matrix(A)`?

I have a file [`hemisphere_masks.h5`](https://drive.google.com/open?id=1x0JKGaMfgeJ2yTtCV0ugx8zzbEwgA6y9).

```julia
julia> @time lm = Matrix(sparse(H5SparseMatrixCSC("/scratch/atlas/ZBrain/hemisphere_masks.h5", "left")));
0.314911
julia> @time lm = Matrix(H5SparseMatrixCSC("/scratch/atlas/ZBrain/hemisphere_masks.h5", "left"))
[5-10+ minutes, I forget]

```

**Comment by severinson** [comment]
Good point. I've updated the docs.
19ec6a7c8d41ed815d53be5d1252e0909176c187 9f064c82d9930b9ab9da7e3a403186153bbb901a
